import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import FormattedTime from "../lib/FormattedTime";
import { getAllStockTransactions } from "../features/stocktransactionSlice";
import { gettingallproducts } from "../features/productSlice";
import toast from "react-hot-toast";
import { ChevronLeft, ChevronRight, FileText } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function StockTransaction() {
  const { Authuser } = useSelector((state) => state.auth);
  const { getallStocks, totalPages, currentPage, isgetallStocks } = useSelector((state) => state.stocktransaction);
  const { getallproduct } = useSelector((state) => state.product);

  const dispatch = useDispatch();

  // Filter States
  const [filterType, setFilterType] = useState("");
  const [filterProduct, setFilterProduct] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [page, setPage] = useState(1);

  useEffect(() => {
    dispatch(gettingallproducts());
  }, [dispatch]);

  useEffect(() => {
    const params = {
      page,
      type: filterType,
      product: filterProduct,
      startDate,
      endDate
    };
    dispatch(getAllStockTransactions(params));
  }, [dispatch, page, filterType, filterProduct, startDate, endDate]);

  const handleExportPDF = () => {
    if (!getallStocks || getallStocks.length === 0) {
      toast.error("No data to export");
      return;
    }

    const doc = new jsPDF();
    const companyName = "Inventory Management System";
    const pageWidth = doc.internal.pageSize.getWidth();

    // ── Header Banner ────────────────────────────────────────────────────────
    doc.setFillColor(30, 41, 59); // #1E293B
    doc.rect(0, 0, pageWidth, 28, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(companyName, 14, 13);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(203, 213, 225); // #CBD5E1
    doc.text("Stock History Report", 14, 21);

    // ── Meta Section ─────────────────────────────────────────────────────────
    doc.setFillColor(248, 250, 252); // #F8FAFC
    doc.rect(14, 32, pageWidth - 28, 14, 'F');
    doc.setDrawColor(226, 232, 240); // #E2E8F0
    doc.rect(14, 32, pageWidth - 28, 14, 'S');

    doc.setFontSize(8);
    doc.setTextColor(55, 65, 81); // #374151
    doc.setFont("helvetica", "bold");

    const dateRange = (startDate || endDate) ? `${startDate || 'Start'} to ${endDate || 'End'}` : "All Time";
    
    doc.text("Period:", 18, 38);
    doc.setFont("helvetica", "normal");
    doc.text(dateRange, 32, 38);

    doc.setFont("helvetica", "bold");
    doc.text("Generated By:", 90, 38);
    doc.setFont("helvetica", "normal");
    doc.text(Authuser?.name || 'Admin', 115, 38);

    doc.setFont("helvetica", "bold");
    doc.text("Date:", 145, 38);
    doc.setFont("helvetica", "normal");
    doc.text(new Date().toLocaleString(), 155, 38);

    // ── Table ────────────────────────────────────────────────────────────────
    const tableColumn = ["Date", "Product", "Type", "Qty", "Mov.", "Prev", "Current", "By"];
    const tableRows = getallStocks.map(log => [
      new Date(log.date || log.createdAt).toLocaleDateString(),
      log.product?.name || "N/A",
      log.type,
      String(log.quantity),
      (log.type === 'IN' || (log.type === 'ADJUST' && log.quantity > 0)) ? "IN" : "OUT",
      String(log.previousStock ?? "-"),
      String(log.currentStock ?? "-"),
      log.performedBy?.name || "System"
    ]);

    autoTable(doc, {
      startY: 50,
      head: [tableColumn],
      body: tableRows,
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8, textColor: [26, 26, 26] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { top: 35, bottom: 25 },
      columnStyles: {
        3: { halign: 'right' }, // Qty
        5: { halign: 'right' }, // Prev
        6: { halign: 'right' }  // Current
      },
      didDrawPage: function (data) {
        // Footer (Page Numbers)
        const str = "Page " + doc.internal.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text(str, pageWidth - 14, doc.internal.pageSize.getHeight() - 10, { align: "right" });
      }
    });

    // ── Totals Summary ───────────────────────────────────────────────────────
    const finalY = doc.lastAutoTable.finalY + 8;
    const totalIn = getallStocks.reduce((acc, log) => (log.type === 'IN' || (log.type === 'ADJUST' && log.quantity > 0)) ? acc + log.quantity : acc, 0);
    const totalOut = getallStocks.reduce((acc, log) => (log.type === 'OUT' || (log.type === 'ADJUST' && log.quantity < 0)) ? acc + Math.abs(log.quantity) : acc, 0);

    doc.setDrawColor(203, 213, 225); // #CBD5E1
    doc.setLineWidth(0.5);
    doc.line(14, finalY, pageWidth - 14, finalY);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text("SUMMARY", 14, finalY + 6);
    
    doc.setFont("helvetica", "normal");
    doc.setTextColor(55, 65, 81);
    doc.text(`Total IN Movement:`, 14, finalY + 12);
    doc.setFont("helvetica", "bold");
    doc.text(String(totalIn), 80, finalY + 12, { align: "right" });

    doc.setFont("helvetica", "normal");
    doc.text(`Total OUT Movement:`, 14, finalY + 17);
    doc.setFont("helvetica", "bold");
    doc.text(String(totalOut), 80, finalY + 17, { align: "right" });

    doc.save(`Stock_History_${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success("PDF Exported successfully");
  };

  return (
    <div className="bg-neutral-50 min-h-screen font-sans text-gray-900 pb-20">

      <div className="px-8 pb-8 pt-4 max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div className="hidden"></div>
          <div className="flex gap-3">
            <button onClick={handleExportPDF} className="bg-primary hover:bg-blue-600 text-white px-6 py-2.5 rounded-xl flex items-center gap-2 shadow-md transition font-bold text-sm">
              <FileText size={18} /> Export PDF
            </button>
          </div>
        </div>

        {/* Simple Filters */}
        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm mb-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 items-end">
            <div>
              <label className="block text-xs font-black uppercase text-gray-400 mb-2 tracking-widest">Movement Type</label>
              <select
                value={filterType}
                onChange={(e) => { setFilterType(e.target.value); setPage(1); }}
                className="input-field w-full h-12 text-sm appearance-none"
              >
                <option value="">All Movements</option>
                <option value="IN">Stock IN</option>
                <option value="OUT">Stock OUT</option>
                <option value="ADJUST">Adjustment</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-black uppercase text-gray-400 mb-2 tracking-widest">Select Product</label>
              <select
                value={filterProduct}
                onChange={(e) => { setFilterProduct(e.target.value); setPage(1); }}
                className="input-field w-full h-12 text-sm appearance-none"
              >
                <option value="">All Products</option>
                {getallproduct?.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-black uppercase text-gray-400 mb-2 tracking-widest">Start Date</label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => { setStartDate(e.target.value); setPage(1); }}
                className="input-field w-full h-12 text-sm"
              />
            </div>
            <div>
              <label className="block text-xs font-black uppercase text-gray-400 mb-2 tracking-widest">End Date</label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => { setEndDate(e.target.value); setPage(1); }}
                className="input-field w-full h-12 text-sm"
              />
            </div>
          </div>
          <div className="mt-6 flex justify-end">
            <button
              onClick={() => { setFilterType(""); setFilterProduct(""); setStartDate(""); setEndDate(""); setPage(1); }}
              className="text-gray-400 hover:text-primary text-xs font-bold uppercase tracking-widest hover:underline transition"
            >
              Reset Filters
            </button>
          </div>
        </div>

        {/* History Table */}
        <div className="card bg-white border border-gray-100 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full text-left">
              <thead className="bg-gray-100 text-gray-500 uppercase text-[11px] font-bold tracking-widest leading-none">
                <tr>
                  <th className="px-6 py-5">Date</th>
                  <th className="px-6 py-5">Product Name</th>
                  <th className="px-6 py-5 text-center">Type</th>
                  <th className="px-6 py-5 text-right">Qty</th>
                  <th className="px-6 py-5 text-center">IN / OUT</th>
                  <th className="px-6 py-5 text-right">Prev Stock</th>
                  <th className="px-6 py-5 text-right">New Stock</th>
                  <th className="px-6 py-5">Created By</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 bg-white">
                {getallStocks?.length > 0 ? (
                  getallStocks.map((log) => {
                    const isIncrease = log.type === 'IN' || (log.type === 'ADJUST' && log.quantity > 0);
                    return (
                      <tr key={log._id} className="hover:bg-blue-50/20 transition group">
                        <td className="px-6 py-4 text-sm text-gray-600 whitespace-nowrap">
                          <FormattedTime timestamp={log.date || log.createdAt} />
                        </td>
                        <td className="px-6 py-4">
                          <div className="font-bold text-gray-800">{log.product?.name || "Deleted Product"}</div>
                          <div className="text-[10px] text-gray-400 uppercase font-semibold tracking-tighter">{log.product?.sku}</div>
                        </td>
                        <td className="px-6 py-4 text-center">
                          <span className="px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider bg-gray-100 text-gray-700 border border-gray-200">
                            {log.type}
                          </span>
                        </td>
                        <td className={`px-6 py-4 text-right font-black ${isIncrease ? 'text-green-600' : 'text-red-500'}`}>
                          {isIncrease ? '+' : '-'}{Math.abs(log.quantity)}
                        </td>
                        <td className="px-6 py-4 text-center">
                          <span className={`px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest ${isIncrease ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {isIncrease ? 'IN' : 'OUT'}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-right text-gray-600 font-mono text-xs">
                          {log.previousStock ?? "-"}
                        </td>
                        <td className="px-6 py-4 text-right font-black text-gray-800 font-mono text-xs">
                          {log.currentStock ?? "-"}
                        </td>
                        <td className="px-6 py-4">
                          <div className="text-sm font-bold text-gray-700">{log.performedBy?.name || "System"}</div>
                          <div className="text-[10px] text-gray-400">{log.performedBy?.role || "SYSTEM"}</div>
                        </td>
                      </tr>
                    )
                  })
                ) : (
                  <tr>
                    <td colSpan="8" className="text-center py-24 bg-gray-50/30">
                      {isgetallStocks ? (
                        <div className="flex flex-col items-center opacity-40">
                          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mb-4"></div>
                          <p className="italic text-gray-500 text-sm">Synchronizing ledger...</p>
                        </div>
                      ) : (
                        <div className="flex flex-col items-center opacity-40">
                          <FileText size={48} className="mb-2 text-gray-300" />
                          <p className="italic text-gray-500 text-sm">No movement history found.</p>
                        </div>
                      )}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="px-6 py-4 bg-gray-50/50 border-t border-gray-100 flex items-center justify-between">
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">
              Page {currentPage} of {totalPages}
            </p>
            <div className="flex gap-2">
              <button
                disabled={currentPage <= 1}
                onClick={() => setPage(currentPage - 1)}
                className="p-2 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 disabled:opacity-30 transition shadow-sm"
              >
                <ChevronLeft size={18} />
              </button>
              <button
                disabled={currentPage >= totalPages}
                onClick={() => setPage(currentPage + 1)}
                className="p-2 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 disabled:opacity-30 transition shadow-sm"
              >
                <ChevronRight size={18} />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default StockTransaction;
